# ---------------
# --- NETWORK ---
# ---------------
networks:
  hexagon_network:
    driver: bridge

# ---------------
# --- VOLUMES ---
# ---------------
volumes:
  hexagon_postgres_data:
  hexagon_mongo_data:

# ----------------
# --- SERVICES ---
# ----------------
services:
  # ----------------
  # --- POSTGRES ---
  # ----------------
  hexagon_postgres:
    image: postgres:latest
    container_name: hexagon_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: hexagon_postgres_database
    volumes:
      - hexagon_postgres_data:/var/lib/postgresql
    networks:
      - hexagon_network
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # ---------------
  # --- MONGODB ---
  # ---------------
  hexagon_mongo:
    image: mongo:latest
    container_name: hexagon_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: hexagon_mongo_database
    volumes:
      - hexagon_mongo_data:/data/db
    networks:
      - hexagon_network
    ports:
      - "27017:27017"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # ---------------
  # --- HEXAGON ---
  # ---------------
  hexagon_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexagon_app
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: hexagon_postgres
      POSTGRES_DATABASE: hexagon_postgres_database
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: hexagon_mongo
      MONGO_DATABASE: hexagon_mongo_database
    ports:
      - "8080:8080"
    depends_on:
      - hexagon_postgres
      - hexagon_mongo
    networks:
      - hexagon_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"