-- Category Table
CREATE TABLE public."category"
(
    "category_id"   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"          VARCHAR(128) NOT NULL UNIQUE,
    "deletion_date" TIMESTAMP DEFAULT NULL
);

-- Product Table
CREATE TABLE public."product"
(
    "product_id"    SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category_id"   SMALLINT     NOT NULL,
    "name"          VARCHAR(128) NOT NULL UNIQUE,
    "description"   VARCHAR(512)          DEFAULT NULL,
    "created_at"    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletion_date" TIMESTAMP             DEFAULT NULL,
    CONSTRAINT fk_product_category_id FOREIGN KEY ("category_id") REFERENCES public."category" ("category_id")
        ON DELETE RESTRICT ON UPDATE CASCADE
);